server:
  port: 8082

spring:
  application:
    name: skills_management
  jpa:
    hibernate:
      dll-auto: update
    show-sql: true
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
